### PR TITLE
Update activity.info to sugar-activity3

### PR DESCRIPTION
**Pull request by srevinsaju**
@quozl I had forgotten to do this

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reveals that https://github.com/godiard/music-keyboard-activity/pull/25 was not tested with Python 3.  Oops.  In testing now, I can't import ctcsound on Python 3.  I see Fedora has it, but Debian and Ubuntu do not.

**Comment by srevinsaju** [comment]
pip3 install ctcsound

**Comment by quozl** [comment]
I had tried that, it failed with an AttributeError and undefined symbol csoundSystemSr.

**Comment by srevinsaju** [comment]
On fedora or ubuntu?

**Comment by quozl** [comment]
Ubuntu 19.04.

**Comment by srevinsaju** [comment]
@quozl is it libcsound64.so not found attribute error?

**Comment by quozl** [comment]
Here's what I see on Ubuntu 19.04

```log
guest@guest:/usr/share/sugar/activities/MusicKeyboard.activity$ sugar-activity3
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activityinstance.py", line 179, in main
    module = __import__(module_name)
  File "/usr/share/sugar/activities/MusicKeyboard.activity/activity.py", line 60, in <module>
    from ttcommon.Util.CSoundClient import new_csound_client
  File "/usr/share/sugar/activities/MusicKeyboard.activity/ttcommon/Util/CSoundClient.py", line 5, in <module>
    import ctcsound
ModuleNotFoundError: No module named 'ctcsound'
guest@guest:/usr/share/sugar/activities/MusicKeyboard.activity$ pip3 install ctcsound
Collecting ctcsound
Requirement already satisfied: numpy>=1.16 in /usr/lib/python3/dist-packages (from ctcsound) (1.16.2)
Installing collected packages: ctcsound
Successfully installed ctcsound-6.13
guest@guest:/usr/share/sugar/activities/MusicKeyboard.activity$ python3 -c 'import ctcsound'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/guest/.local/lib/python3.7/site-packages/ctcsound.py", line 246, in <module>
    libcsound.csoundSystemSr.restype = MYFLT
  File "/usr/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/libcsound64.so: undefined symbol: csoundSystemSr
guest@guest:/usr/share/sugar/activities/MusicKeyboard.activity$ sugar-activity3
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activityinstance.py", line 179, in main
    module = __import__(module_name)
  File "/usr/share/sugar/activities/MusicKeyboard.activity/activity.py", line 60, in <module>
    from ttcommon.Util.CSoundClient import new_csound_client
  File "/usr/share/sugar/activities/MusicKeyboard.activity/ttcommon/Util/CSoundClient.py", line 5, in <module>
    import ctcsound
  File "/home/guest/.local/lib/python3.7/site-packages/ctcsound.py", line 246, in <module>
    libcsound.csoundSystemSr.restype = MYFLT
  File "/usr/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/libcsound64.so: undefined symbol: csoundSystemSr
guest@guest:/usr/share/sugar/activities/MusicKeyboard.activity$ █
```

It may mean that the PyPi package for ctcsound is of a different release compared to the libcsound64-6.0 package.  Checking the versions; from above we can see that pip3 installs 6.13, and from `dpkg-query -W` the version of libcsound64-6.0 is 6.12.2.

**Comment by srevinsaju** [comment]
@quozl Install the csound-dev package, and that error would be fixed

**Comment by quozl** [comment]
There's no such package `csound-dev`, what is the package name?  Here is what is installed on my Ubuntu 19.04 VMs

```log
# dpkg-query -W | egrep 'csound|csnd'
csound  1:6.12.2~dfsg-3
csound-data     1:6.12.2~dfsg-3
csound-utils    1:6.12.2~dfsg-3
libcsnd-dev     1:6.12.2~dfsg-3
libcsnd6-6.0v5  1:6.12.2~dfsg-3
libcsound64-6.0 1:6.12.2~dfsg-3
libcsound64-dev 1:6.12.2~dfsg-3
python-csound   1:6.12.2~dfsg-3
```

**Comment by srevinsaju** [comment]
@quozl try this https://github.com/csound/ctcsound/issues/6#issuecomment-345277219

**Comment by quozl** [comment]
`/usr/lib/libcsound64.so` is already a symbolic link to `libcsound64.so.6.0`.  objdump -T shows csoundCompileTreeAsync is present, but csoundSystemSr is not.

**Comment by srevinsaju** [comment]
@quozl check if 
```
 ss@srevinsaju  ~  pip3 list | grep ctcsound
ctcsound           6.13  
```
and 
```
 ss@srevinsaju  ~ csound -v                        
0dBFS level = 32768.0
--Csound version 6.13 (double samples) Dec 25 2019
```
coincides with the same version, if it doesn't upgrade or downgrade packages accordingly

**Comment by quozl** [comment]
Can't easily do that.  On this version of Ubuntu there's no package for 6.13, and no Python 3 package for ctcsound.  This will effect all activities that use Csound.  Thanks for drawing it to our attention.

**Comment by quozl** [comment]
https://salsa.debian.org/multimedia-team/csound/commit/5f822826e6e9c9c07bad97f097d6fbb111be123c from two days ago is Debian packaging changes to adopt Python 3 support in the Csound package.

**Comment by quozl** [comment]
I built the Debian package from git and tested this branch, thanks.

**Comment by srevinsaju** [comment]
:+1:

**Pull request merged**
